### ISSUE TITLE
Crash link in the description: Error 404

### ISSUE THREAD

**Issue by cabustillo13** [poliastro/lightning-talk#3]
En la descripción tienen el siguiente link: https://nbviewer.jupyter.org/format/slides/github/poliastro/lightning-talk/blob/master/Going%20to%20Mars%20in%205%20minutes.ipynb
Y devuelve un error 404.

Ese link lo pueden reemplazar por el siguiente, que funciona correctamente:
https://nbviewer.jupyter.org/github/poliastro/lightning-talk/blob/main/Going%20to%20Mars%20in%205%20minutes.ipynb

¡Admiro lo que hacen! Es impresionante el trabajo y dedicación que le ponen.

Saludos,
Carlos.

**Comment by astrojuanlu** [comment]
¡Muchas gracias @cabustillo13! Lo acabo de cambiar :) Y gracias por tus palabras también, si algún día quieres colaborar con el proyecto eres más que bienvenido a nuestro chat.

¡Saludos!
